server:
  port: 8080
analytics:
# 需要统计的省分
  analyticsProvince:
    - 内蒙华为
    - 内蒙烽火
# 需要统计的app_id
  recommendIdList:
    - 1
# 需要统计的触发项
  triggerList:
    - DUI430
# 华为内部订购标识（内蒙华为专属）
  huaweiInsideRecommendList:
    - nmghyyby@208
# 常规内容appId前缀标识
  conventionIdPrefix: V

logging:
  file:
    path: ./log

